CREATE AVAILABILITY GROUP Accounts
WITH (
	AUTOMATED_BACKUP_PREFERENCE = PRIMARY,
	DB_FAILOVER = OFF,
	DTC_SUPPORT = NONE,
	REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 0
)
FOR 
REPLICA ON 
	'CLUSTERNODE1\PROD' WITH (
		ENDPOINT_URL = N'TCP://CLUSTERNODE1.AlwaysOn.com:5022', 
		FAILOVER_MODE = AUTOMATIC, 
		AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, 
		SESSION_TIMEOUT = 10, 
		BACKUP_PRIORITY = 50, 
		SEEDING_MODE = MANUAL, 
		PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), 
		SECONDARY_ROLE(ALLOW_CONNECTIONS = NO)
	),
	'CLUSTERNODE2\SYNCHA' WITH (
		ENDPOINT_URL = N'TCP://CLUSTERNODE2.AlwaysOn.com:5022', 
		FAILOVER_MODE = AUTOMATIC, 
		AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, 
		SESSION_TIMEOUT = 10, 
		BACKUP_PRIORITY = 50, 
		SEEDING_MODE = MANUAL, 
		PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), 
		SECONDARY_ROLE(ALLOW_CONNECTIONS = NO)
	),
	'CLUSTERNODE3\ASYNCDR' WITH (
		ENDPOINT_URL = N'TCP://CLUSTERNODE3.AlwaysOn.com:5022', 
		FAILOVER_MODE = MANUAL, 
		AVAILABILITY_MODE = ASYNCHRONOUS_COMMIT, 
		SESSION_TIMEOUT = 10, 
		BACKUP_PRIORITY = 50, 
		SEEDING_MODE = MANUAL, 
		PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), 
		SECONDARY_ROLE(ALLOW_CONNECTIONS = NO)
	);
GO
