USE master
GO

CREATE AVAILABILITY GROUP LinuxAOAG WITH (
	AUTOMATED_BACKUP_PREFERENCE = PRIMARY,
	DB_FAILOVER = OFF,
	DTC_SUPPORT = NONE,
	CLUSTER_TYPE = EXTERNAL,
	REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT = 0
)
FOR DATABASE Sales
REPLICA ON 
	'linuxconfig' WITH (
		ENDPOINT_URL = 'TCP://linuxconfig.AlwaysOn.com:5022', 
		AVAILABILITY_MODE = CONFIGURATION_ONLY
	),
	'linuxprod' WITH (
		ENDPOINT_URL = 'TCP://linuxprod.AlwaysOn.com:5022', 
		FAILOVER_MODE = EXTERNAL, 
		AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, 
		SESSION_TIMEOUT = 10, 
		BACKUP_PRIORITY = 50, 
		SEEDING_MODE = MANUAL, 
		PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), 
		SECONDARY_ROLE(ALLOW_CONNECTIONS = NO)
	),
	'linuxsyncha' WITH (
		ENDPOINT_URL = 'TCP://linuxsyncha.AlwaysOn.com:5022', 
		FAILOVER_MODE = EXTERNAL, 
		AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, 
		SESSION_TIMEOUT = 10, 
		BACKUP_PRIORITY = 0, 
		SEEDING_MODE = MANUAL, 
		PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), 
		SECONDARY_ROLE(ALLOW_CONNECTIONS = NO)
	) ;
GO
